# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kv.proto',
  package='kv_store',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08kv.proto\x12\x08kv_store\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\x05\"\'\n\x05Value\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0f\n\x07\x64\x65\x66ined\x18\x02 \x01(\x08\")\n\x0bNewKeyValue\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05\"\x06\n\x04Void\"\x1a\n\nStoredKeys\x12\x0c\n\x04keys\x18\x01 \x03(\x05\x32\x93\x01\n\x02KV\x12\'\n\x03get\x12\r.kv_store.Key\x1a\x0f.kv_store.Value\"\x00\x12.\n\x03put\x12\x15.kv_store.NewKeyValue\x1a\x0e.kv_store.Void\"\x00\x12\x34\n\ngetAllKeys\x12\x0e.kv_store.Void\x1a\x14.kv_store.StoredKeys\"\x00\x62\x06proto3'
)




_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='kv_store.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kv_store.Key.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=40,
)


_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='kv_store.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='kv_store.Value.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='defined', full_name='kv_store.Value.defined', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=81,
)


_NEWKEYVALUE = _descriptor.Descriptor(
  name='NewKeyValue',
  full_name='kv_store.NewKeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kv_store.NewKeyValue.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='kv_store.NewKeyValue.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=124,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='kv_store.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=132,
)


_STOREDKEYS = _descriptor.Descriptor(
  name='StoredKeys',
  full_name='kv_store.StoredKeys',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='kv_store.StoredKeys.keys', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=160,
)

DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['Value'] = _VALUE
DESCRIPTOR.message_types_by_name['NewKeyValue'] = _NEWKEYVALUE
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['StoredKeys'] = _STOREDKEYS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv_store.Key)
  })
_sym_db.RegisterMessage(Key)

Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), {
  'DESCRIPTOR' : _VALUE,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv_store.Value)
  })
_sym_db.RegisterMessage(Value)

NewKeyValue = _reflection.GeneratedProtocolMessageType('NewKeyValue', (_message.Message,), {
  'DESCRIPTOR' : _NEWKEYVALUE,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv_store.NewKeyValue)
  })
_sym_db.RegisterMessage(NewKeyValue)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv_store.Void)
  })
_sym_db.RegisterMessage(Void)

StoredKeys = _reflection.GeneratedProtocolMessageType('StoredKeys', (_message.Message,), {
  'DESCRIPTOR' : _STOREDKEYS,
  '__module__' : 'kv_pb2'
  # @@protoc_insertion_point(class_scope:kv_store.StoredKeys)
  })
_sym_db.RegisterMessage(StoredKeys)



_KV = _descriptor.ServiceDescriptor(
  name='KV',
  full_name='kv_store.KV',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=163,
  serialized_end=310,
  methods=[
  _descriptor.MethodDescriptor(
    name='get',
    full_name='kv_store.KV.get',
    index=0,
    containing_service=None,
    input_type=_KEY,
    output_type=_VALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='put',
    full_name='kv_store.KV.put',
    index=1,
    containing_service=None,
    input_type=_NEWKEYVALUE,
    output_type=_VOID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getAllKeys',
    full_name='kv_store.KV.getAllKeys',
    index=2,
    containing_service=None,
    input_type=_VOID,
    output_type=_STOREDKEYS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_KV)

DESCRIPTOR.services_by_name['KV'] = _KV

# @@protoc_insertion_point(module_scope)
