# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kv_pb2 as kv__pb2


class KVStub(object):
    """Definição cliente-servidor

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get = channel.unary_unary(
                '/kv_store.KV/get',
                request_serializer=kv__pb2.Key.SerializeToString,
                response_deserializer=kv__pb2.Value.FromString,
                )
        self.put = channel.unary_unary(
                '/kv_store.KV/put',
                request_serializer=kv__pb2.NewKeyValue.SerializeToString,
                response_deserializer=kv__pb2.Void.FromString,
                )
        self.getAllKeys = channel.unary_unary(
                '/kv_store.KV/getAllKeys',
                request_serializer=kv__pb2.Void.SerializeToString,
                response_deserializer=kv__pb2.StoredKeys.FromString,
                )


class KVServicer(object):
    """Definição cliente-servidor

    """

    def get(self, request, context):
        """"Pega" uma chave de um seridor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def put(self, request, context):
        """Define uma chave ao servidor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAllKeys(self, request, context):
        """Lista todas as chaves contidas no servidor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVServicer_to_server(servicer, server) -> object:
    rpc_method_handlers = {
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=kv__pb2.Key.FromString,
                    response_serializer=kv__pb2.Value.SerializeToString,
            ),
            'put': grpc.unary_unary_rpc_method_handler(
                    servicer.put,
                    request_deserializer=kv__pb2.NewKeyValue.FromString,
                    response_serializer=kv__pb2.Void.SerializeToString,
            ),
            'getAllKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.getAllKeys,
                    request_deserializer=kv__pb2.Void.FromString,
                    response_serializer=kv__pb2.StoredKeys.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kv_store.KV', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KV(object):
    """Definição cliente-servidor

    """

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kv_store.KV/get',
            kv__pb2.Key.SerializeToString,
            kv__pb2.Value.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kv_store.KV/put',
            kv__pb2.NewKeyValue.SerializeToString,
            kv__pb2.Void.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAllKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kv_store.KV/getAllKeys',
            kv__pb2.Void.SerializeToString,
            kv__pb2.StoredKeys.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
